/**
 * Created by Yilan丶 on 2018/12/12.
 */
var goods={
    //中餐
    Chinese_food:{
        Chinese_food_1:{
            name:"豆花生",
            price:"5",
            src:"images/豆花生.jpg"
        },
        Chinese_food_2:{
            name:"豆角炒叉烧片",
            price:"12",
            src:"images/豆角炒叉烧片.jpg"
        },
        Chinese_food_3:{
            name:"风味意大利粉面",
            price:"28",
            src:"images/风味意大利粉面.jpg"
        },
        Chinese_food_4:{
            name:"花生炒牛肉",
            price:"15",
            src:"images/花生炒牛肉.jpg"
        },
        Chinese_food_5:{
            name:"尖椒炒牛肉",
            price:"18",
            src:"images/尖椒炒牛肉.jpg"
        },
        Chinese_food_6:{
            name:"龙虾拼盘",
            price:"38",
            src:"images/龙虾拼盘.jpg"
        },
        Chinese_food_7:{
            name:"牛腩拼虾面",
            price:"22",
            src:"images/牛腩拼虾面.jpg"
        },
        Chinese_food_8:{
            name:"芹菜叉烧肉",
            price:"13",
            src:"images/芹菜叉烧肉.jpg"
        },
        Chinese_food_9:{
            name:"芹菜炒透抽",
            price:"12",
            src:"images/芹菜炒透抽.jpg"
        },
        Chinese_food_10:{
            name:"时蔬青菜",
            price:"10",
            src:"images/时蔬青菜.jpg"
        },
        Chinese_food_11:{
            name:"酸菜炒肉片",
            price:"14",
            src:"images/酸菜炒肉片.jpg"
        },
    },
    //热销
    hot_product:{
        hot_product_1:{
            name:"酸辣豆腐片",
            price:"13",
            src:"images/酸辣豆腐片.jpg"
        },
        hot_product_2:{
            name:"酸辣牛肉面",
            price:"16",
            src:"images/酸辣牛肉面.jpg"
        },
        hot_product_3:{
            name:"酸辣鱼",
            price:"20",
            src:"images/酸辣鱼.jpg"
        },
        hot_product_4:{
            name:"虾球猪手",
            price:"15",
            src:"images/虾球猪手.jpg"
        },
        hot_product_5:{
            name:"香辣鱼",
            price:"18",
            src:"images/香辣鱼.jpg"
        }
    },
    //西餐   
    Western_style_food:{
        Western_style_food_1:{
            name:"风味葡挞",
            price:"3",
            src:"images/风味葡挞.jpg"
        },
        Western_style_food_2:{
            name:"鸡块",
            price:"6",
            src:"images/鸡块.jpg"
        },
        Western_style_food_3:{
            name:"鸡肉卷",
            price:"12",
            src:"images/鸡肉卷.jpg"
        },
        Western_style_food_4:{
            name:"牛肉饼汉堡",
            price:"15",
            src:"images/牛肉饼汉堡.jpg"
        },
        Western_style_food_5:{
            name:"香煎鸡排",
            price:"7",
            src:"images/香煎鸡排.jpg"
        },
        Western_style_food_6:{
            name:"芋丸",
            price:"5",
            src:"images/风味意大利粉面.jpg"
        },
        Western_style_food_7:{
            name:"至尊奥尔良披萨",
            price:"58",
            src:"images/至尊奥尔良披萨.jpg"
        },
    },
    //西式套餐
    Western_style_package:{
        Western_style_package_1:{
            name:"情侣套餐",
            price:"32",
            src:"images/情侣套餐.jpg"
        },
        Western_style_package_2:{
            name:"全家桶套餐",
            price:"102",
            src:"images/全家桶套餐.jpg"
        },
        Western_style_package_3:{
            name:"小食两件套",
            price:"12",
            src:"images/小食两件套.jpg"
        },
    },
    //主食--米饭
    rice:{
        rice_1:{
            name:"米饭",
            price:"2.00",
            src:"images/米饭.jpg"
        }
    },
    //饮料
    Drinks:{
        Drinks_1:{
            name:"橙汁",
            price:"8",
            src:"images/橙汁.jpg"
        },
        Drinks_2:{
            name:"可乐",
            price:"6.5",
            src:"images/可乐.jpg"
        },
        Drinks_3:{
            name:"美年达",
            price:"6.5",
            src:"images/美年达.jpg"
        },
        Drinks_4:{
            name:"雪碧",
            price:"6.5",
            src:"images/雪碧.jpg"
        },
    },
    //调味料
    Seasoning:{
        Seasoning_1:{
            name:"番茄酱",
            price:"0.1",
            src:"images/番茄酱.jpg"
        },
        Seasoning_2:{
            name:"胡椒粉",
            price:"0.1",
            src:"images/胡椒粉.jpg"
        },
        Seasoning_3:{
            name:"花生酱",
            price:"0.1",
            src:"images/花生酱.jpg"
        },
        Seasoning_4:{
            name:"辣椒酱",
            price:"0.1",
            src:"images/辣椒酱.jpg"
        },
        Seasoning_5:{
            name:"孜然粉",
            price:"0.1",
            src:"images/孜然粉.jpg"
        },
    } 
}

